GET http://localhost:5146/games


###
GET http://localhost:5146/games/5

###
POST http://localhost:5146/games
Content-Type: application/json

{
    "name": "GamedwqdqwGamedwqdqwGamedwqdqwGamedwqdqwGamedwqdqwGamedwqdqwGamedwqdqwGamedwqdqwGamedwqdqwGamedwqdqwGamedwqdqw",
    "genre": "Slice of Life",
    "price": 29.99,
    "releaseDate": "2019-11-18"
}

###
PUT http://localhost:5146/games/5
Content-Type: application/json

{
    "name": "Wukong",
    "genre": "Adventure",
    "price": 19.99,
    "releaseDate": "2020-05-01"
}

###
DELETE http://localhost:5146/games/3